[build]
	command = "npm run build"
	functions = "functions-build/"
	publish = "build"
	command="echo 'message'"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/:splat"
  status = 200
	force = true